[package]
name = "execute_testcase"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
async-std = {workspace = true}
async-trait = {workspace = true}
model={path="../model"}
polars = {workspace = true}
service={path="../service"}
strum = {workspace = true}
strum_macros = {workspace = true}
tokio = {workspace = true}
