[package]
name = "model"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version="0.4.41", features=["serde"]}
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.142"
tiberius = {version = "0.12.3", features=["chrono"]}
tiberius-mappers = "0.7.0"
