[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
calamine = {workspace = true}
chrono = {workspace = true}
model = {path="../model"}
repository = {path="../repository"}
serde_json = {workspace = true}
serde = {workspace = true}
futures = {workspace = true}
tokio = {workspace = true}
csv-async = {workspace = true}
async-std = {workspace = true}
