[package]
name = "repository"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
async-std = {workspace = true}
tiberius = {workspace = true}
model={path="../model"}
serde_json = {workspace = true}
tiberius-mappers = {workspace = true}
async-trait = {workspace = true}
sqlx = {workspace = true}
